networks:
  ai_network-01:
    driver: bridge

services:
  latentsync-01:
    image: latentsync:1.5
    container_name: latentsync-01
    restart: always
    runtime: nvidia
    privileged: true
    volumes:
      - d:/AI/LatentSync/results01:/code/results
      - d:/AI/LatentSync/error01:/code/error
    environment:
      - TQDM_DISABLE=1 # 全局关闭进度条显示
      - PYTHONUNBUFFERED=1 # 取消标准输出缓冲
      - CUDA_VISIBLE_DEVICES=3
      - PYTORCH_CUDA_ALLOC_CONF=max_split_size_mb:1024
    tty: true  # 分配伪终端
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [ gpu ]
    shm_size: '32g'
    ports:
      - '17810:7810'
    command: python /code/api.py --num_frames 24
    networks:
      - ai_network-01
